{{- if or .Values.configMap.enabled .Values.mail.enabled .Values.awsS3.enabled .Values.initdFromChart.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataverseup.fullname" . }}-config
  labels:
    {{- include "dataverseup.labels" . | nindent 4 }}
data:
  {{- if .Values.initdFromChart.enabled }}
  {{- range $path, $bytes := .Files.Glob "files/init.d/*.sh" }}
  {{ base $path }}: |
{{- $bytes | toString | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.configMap.enabled }}
  {{- toYaml .Values.configMap.data | nindent 2 }}
  {{- end }}
  {{- else }}
  {{- if .Values.configMap.enabled }}
  {{- toYaml .Values.configMap.data | nindent 2 }}
  {{- end }}
  {{- if .Values.mail.enabled }}
  {{- $mailScript := .Files.Get "files/010-mailrelay-set.sh" | trim }}
  010-mailrelay-set.sh: |
{{- $mailScript | nindent 4 }}
  {{- end }}
  {{- if .Values.awsS3.enabled }}
  {{- $s3Script := .Files.Get "files/006-s3-aws-storage.sh" | trim }}
  006-s3-aws-storage.sh: |
{{- $s3Script | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
