{{- if and .Values.docrootPersistence.enabled (empty (.Values.docrootPersistence.existingClaim | default "")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dataverseup.fullname" . }}-docroot
  labels:
    {{- include "dataverseup.labels" . | nindent 4 }}
    app.kubernetes.io/component: docroot
spec:
  accessModes:
    - {{ .Values.docrootPersistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.docrootPersistence.size | quote }}
  {{- with .Values.docrootPersistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
